linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert

linters-settings:
  govet:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: com.moguyn/mcp-go-search

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

run:
  timeout: 5m 